# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlvc_api/dlvc_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dlvc_api import dlvc_pb2 as dlvc__api_dot_dlvc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlvc_api/dlvc_api.proto',
  package='dlvc_api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x64lvc_api/dlvc_api.proto\x12\x08\x64lvc_api\x1a\x13\x64lvc_api/dlvc.proto2\xda\x04\n\x0b\x44LVCService\x12S\n\x0ePushRawMessage\x12\x1f.dlvc_api.PushRawMessageRequest\x1a .dlvc_api.PushRawMessageResponse\x12V\n\x0fPushRawMessages\x12 .dlvc_api.PushRawMessagesRequest\x1a!.dlvc_api.PushRawMessagesResponse\x12P\n\rGetRawMessage\x12\x1e.dlvc_api.GetRawMessageRequest\x1a\x1f.dlvc_api.GetRawMessageResponse\x12S\n\x0eGetRawMessages\x12\x1f.dlvc_api.GetRawMessagesRequest\x1a .dlvc_api.GetRawMessagesResponse\x12\x44\n\tSummarize\x12\x1a.dlvc_api.SummarizeRequest\x1a\x1b.dlvc_api.SummarizeResponse\x12_\n\x12ListMetadataValues\x12#.dlvc_api.ListMetadataValuesRequest\x1a$.dlvc_api.ListMetadataValuesResponse\x12P\n\rListExercises\x12\x1e.dlvc_api.ListExercisesRequest\x1a\x1f.dlvc_api.ListExercisesResponseb\x06proto3')
  ,
  dependencies=[dlvc__api_dot_dlvc__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DLVCSERVICE = _descriptor.ServiceDescriptor(
  name='DLVCService',
  full_name='dlvc_api.DLVCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=59,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushRawMessage',
    full_name='dlvc_api.DLVCService.PushRawMessage',
    index=0,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._PUSHRAWMESSAGEREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._PUSHRAWMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PushRawMessages',
    full_name='dlvc_api.DLVCService.PushRawMessages',
    index=1,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._PUSHRAWMESSAGESREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._PUSHRAWMESSAGESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRawMessage',
    full_name='dlvc_api.DLVCService.GetRawMessage',
    index=2,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._GETRAWMESSAGEREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._GETRAWMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRawMessages',
    full_name='dlvc_api.DLVCService.GetRawMessages',
    index=3,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._GETRAWMESSAGESREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._GETRAWMESSAGESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Summarize',
    full_name='dlvc_api.DLVCService.Summarize',
    index=4,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._SUMMARIZEREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._SUMMARIZERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListMetadataValues',
    full_name='dlvc_api.DLVCService.ListMetadataValues',
    index=5,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._LISTMETADATAVALUESREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._LISTMETADATAVALUESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListExercises',
    full_name='dlvc_api.DLVCService.ListExercises',
    index=6,
    containing_service=None,
    input_type=dlvc__api_dot_dlvc__pb2._LISTEXERCISESREQUEST,
    output_type=dlvc__api_dot_dlvc__pb2._LISTEXERCISESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DLVCSERVICE)

DESCRIPTOR.services_by_name['DLVCService'] = _DLVCSERVICE

# @@protoc_insertion_point(module_scope)
