// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlvc_api/dlvc_api.proto

package dlvc_api;

public final class DlvcApi {
  private DlvcApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027dlvc_api/dlvc_api.proto\022\010dlvc_api\032\023dlv" +
      "c_api/dlvc.proto2\332\004\n\013DLVCService\022S\n\016Push" +
      "RawMessage\022\037.dlvc_api.PushRawMessageRequ" +
      "est\032 .dlvc_api.PushRawMessageResponse\022V\n" +
      "\017PushRawMessages\022 .dlvc_api.PushRawMessa" +
      "gesRequest\032!.dlvc_api.PushRawMessagesRes" +
      "ponse\022P\n\rGetRawMessage\022\036.dlvc_api.GetRaw" +
      "MessageRequest\032\037.dlvc_api.GetRawMessageR" +
      "esponse\022S\n\016GetRawMessages\022\037.dlvc_api.Get" +
      "RawMessagesRequest\032 .dlvc_api.GetRawMess" +
      "agesResponse\022D\n\tSummarize\022\032.dlvc_api.Sum" +
      "marizeRequest\032\033.dlvc_api.SummarizeRespon" +
      "se\022_\n\022ListMetadataValues\022#.dlvc_api.List" +
      "MetadataValuesRequest\032$.dlvc_api.ListMet" +
      "adataValuesResponse\022P\n\rListExercises\022\036.d" +
      "lvc_api.ListExercisesRequest\032\037.dlvc_api." +
      "ListExercisesResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dlvc_api.Dlvc.getDescriptor(),
        });
    dlvc_api.Dlvc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
