// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlvc_api/dlvc_api.proto

#include "dlvc_api/dlvc_api.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace dlvc_api {
}  // namespace dlvc_api
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_dlvc_5fapi_2fdlvc_5fapi_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_dlvc_5fapi_2fdlvc_5fapi_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_dlvc_5fapi_2fdlvc_5fapi_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_dlvc_5fapi_2fdlvc_5fapi_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_dlvc_5fapi_2fdlvc_5fapi_2eproto[] =
  "\n\027dlvc_api/dlvc_api.proto\022\010dlvc_api\032\023dlv"
  "c_api/dlvc.proto2\332\004\n\013DLVCService\022S\n\016Push"
  "RawMessage\022\037.dlvc_api.PushRawMessageRequ"
  "est\032 .dlvc_api.PushRawMessageResponse\022V\n"
  "\017PushRawMessages\022 .dlvc_api.PushRawMessa"
  "gesRequest\032!.dlvc_api.PushRawMessagesRes"
  "ponse\022P\n\rGetRawMessage\022\036.dlvc_api.GetRaw"
  "MessageRequest\032\037.dlvc_api.GetRawMessageR"
  "esponse\022S\n\016GetRawMessages\022\037.dlvc_api.Get"
  "RawMessagesRequest\032 .dlvc_api.GetRawMess"
  "agesResponse\022D\n\tSummarize\022\032.dlvc_api.Sum"
  "marizeRequest\032\033.dlvc_api.SummarizeRespon"
  "se\022_\n\022ListMetadataValues\022#.dlvc_api.List"
  "MetadataValuesRequest\032$.dlvc_api.ListMet"
  "adataValuesResponse\022P\n\rListExercises\022\036.d"
  "lvc_api.ListExercisesRequest\032\037.dlvc_api."
  "ListExercisesResponseb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_deps[1] = {
  &::descriptor_table_dlvc_5fapi_2fdlvc_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_once;
static bool descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto = {
  &descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_initialized, descriptor_table_protodef_dlvc_5fapi_2fdlvc_5fapi_2eproto, "dlvc_api/dlvc_api.proto", 669,
  &descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_once, descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_sccs, descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_dlvc_5fapi_2fdlvc_5fapi_2eproto::offsets,
  file_level_metadata_dlvc_5fapi_2fdlvc_5fapi_2eproto, 0, file_level_enum_descriptors_dlvc_5fapi_2fdlvc_5fapi_2eproto, file_level_service_descriptors_dlvc_5fapi_2fdlvc_5fapi_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_dlvc_5fapi_2fdlvc_5fapi_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_dlvc_5fapi_2fdlvc_5fapi_2eproto), true);
namespace dlvc_api {

// @@protoc_insertion_point(namespace_scope)
}  // namespace dlvc_api
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
