// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dlvc_api/dlvc.proto

package dlvc_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRetrievalType int32

const (
	MessageRetrievalType_UNSPECIFIED           MessageRetrievalType = 0
	MessageRetrievalType_INDEX                 MessageRetrievalType = 1
	MessageRetrievalType_TIME                  MessageRetrievalType = 2
	MessageRetrievalType_MESSAGE_TYPE          MessageRetrievalType = 3
	MessageRetrievalType_ENCODING_TYPE         MessageRetrievalType = 4
	MessageRetrievalType_METADATA              MessageRetrievalType = 5
	MessageRetrievalType_USER_DEFINED_METADATA MessageRetrievalType = 6
	MessageRetrievalType_POSITION_BOUNDING_BOX MessageRetrievalType = 7
)

var MessageRetrievalType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "INDEX",
	2: "TIME",
	3: "MESSAGE_TYPE",
	4: "ENCODING_TYPE",
	5: "METADATA",
	6: "USER_DEFINED_METADATA",
	7: "POSITION_BOUNDING_BOX",
}

var MessageRetrievalType_value = map[string]int32{
	"UNSPECIFIED":           0,
	"INDEX":                 1,
	"TIME":                  2,
	"MESSAGE_TYPE":          3,
	"ENCODING_TYPE":         4,
	"METADATA":              5,
	"USER_DEFINED_METADATA": 6,
	"POSITION_BOUNDING_BOX": 7,
}

func (x MessageRetrievalType) String() string {
	return proto.EnumName(MessageRetrievalType_name, int32(x))
}

func (MessageRetrievalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{0}
}

type ReturnedMetadataType int32

const (
	ReturnedMetadataType_RETURN_UNSPECIFIED           ReturnedMetadataType = 0
	ReturnedMetadataType_RETURN_NONE                  ReturnedMetadataType = 1
	ReturnedMetadataType_RETURN_ALL                   ReturnedMetadataType = 2
	ReturnedMetadataType_RETURN_TIME                  ReturnedMetadataType = 3
	ReturnedMetadataType_RETURN_SOURCE_TYPE           ReturnedMetadataType = 4
	ReturnedMetadataType_RETURN_METADATA              ReturnedMetadataType = 5
	ReturnedMetadataType_RETURN_USER_DEFINED_METADATA ReturnedMetadataType = 6
	ReturnedMetadataType_RETURN_POSITION              ReturnedMetadataType = 7
)

var ReturnedMetadataType_name = map[int32]string{
	0: "RETURN_UNSPECIFIED",
	1: "RETURN_NONE",
	2: "RETURN_ALL",
	3: "RETURN_TIME",
	4: "RETURN_SOURCE_TYPE",
	5: "RETURN_METADATA",
	6: "RETURN_USER_DEFINED_METADATA",
	7: "RETURN_POSITION",
}

var ReturnedMetadataType_value = map[string]int32{
	"RETURN_UNSPECIFIED":           0,
	"RETURN_NONE":                  1,
	"RETURN_ALL":                   2,
	"RETURN_TIME":                  3,
	"RETURN_SOURCE_TYPE":           4,
	"RETURN_METADATA":              5,
	"RETURN_USER_DEFINED_METADATA": 6,
	"RETURN_POSITION":              7,
}

func (x ReturnedMetadataType) String() string {
	return proto.EnumName(ReturnedMetadataType_name, int32(x))
}

func (ReturnedMetadataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{1}
}

type WrappedMessage_MessageType int32

const (
	WrappedMessage_UNSPECIFIED        WrappedMessage_MessageType = 0
	WrappedMessage_CUSTOM             WrappedMessage_MessageType = 1
	WrappedMessage_DIS7               WrappedMessage_MessageType = 2
	WrappedMessage_COT                WrappedMessage_MessageType = 3
	WrappedMessage_LINK16             WrappedMessage_MessageType = 4
	WrappedMessage_JREAP              WrappedMessage_MessageType = 5
	WrappedMessage_INSTRUCTOR_COMMENT WrappedMessage_MessageType = 6
)

var WrappedMessage_MessageType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CUSTOM",
	2: "DIS7",
	3: "COT",
	4: "LINK16",
	5: "JREAP",
	6: "INSTRUCTOR_COMMENT",
}

var WrappedMessage_MessageType_value = map[string]int32{
	"UNSPECIFIED":        0,
	"CUSTOM":             1,
	"DIS7":               2,
	"COT":                3,
	"LINK16":             4,
	"JREAP":              5,
	"INSTRUCTOR_COMMENT": 6,
}

func (x WrappedMessage_MessageType) String() string {
	return proto.EnumName(WrappedMessage_MessageType_name, int32(x))
}

func (WrappedMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{17, 0}
}

type Metadata_ForceColor int32

const (
	Metadata_UNSPECIFIED Metadata_ForceColor = 0
	Metadata_BLUE        Metadata_ForceColor = 1
	Metadata_RED         Metadata_ForceColor = 2
	Metadata_WHITE       Metadata_ForceColor = 3
	Metadata_GREEN       Metadata_ForceColor = 4
)

var Metadata_ForceColor_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "BLUE",
	2: "RED",
	3: "WHITE",
	4: "GREEN",
}

var Metadata_ForceColor_value = map[string]int32{
	"UNSPECIFIED": 0,
	"BLUE":        1,
	"RED":         2,
	"WHITE":       3,
	"GREEN":       4,
}

func (x Metadata_ForceColor) String() string {
	return proto.EnumName(Metadata_ForceColor_name, int32(x))
}

func (Metadata_ForceColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{18, 0}
}

type MessageEncoding_EncodingType int32

const (
	MessageEncoding_UNSPECIFIED MessageEncoding_EncodingType = 0
	MessageEncoding_CUSTOM      MessageEncoding_EncodingType = 1
	MessageEncoding_TEXT        MessageEncoding_EncodingType = 2
	MessageEncoding_JSON        MessageEncoding_EncodingType = 3
	MessageEncoding_XML         MessageEncoding_EncodingType = 4
	MessageEncoding_CSV         MessageEncoding_EncodingType = 5
)

var MessageEncoding_EncodingType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CUSTOM",
	2: "TEXT",
	3: "JSON",
	4: "XML",
	5: "CSV",
}

var MessageEncoding_EncodingType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CUSTOM":      1,
	"TEXT":        2,
	"JSON":        3,
	"XML":         4,
	"CSV":         5,
}

func (x MessageEncoding_EncodingType) String() string {
	return proto.EnumName(MessageEncoding_EncodingType_name, int32(x))
}

func (MessageEncoding_EncodingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{20, 0}
}

type Position_TFOM int32

const (
	Position_UNSPECIFIED          Position_TFOM = 0
	Position_LTE_1_NANOSECOND     Position_TFOM = 1
	Position_LTE_10_NANOSECONDS   Position_TFOM = 2
	Position_LTE_100_NANOSECONDS  Position_TFOM = 3
	Position_LTE_1_MICROSECOND    Position_TFOM = 4
	Position_LTE_10_MICROSECONDS  Position_TFOM = 5
	Position_LTE_100_MICROSECONDS Position_TFOM = 6
	Position_LTE_1_MILLISECOND    Position_TFOM = 7
	Position_LTE_10_MILLISECONDS  Position_TFOM = 8
	Position_LTE_100_MILLISECONDS Position_TFOM = 9
	Position_LTE_1_SECOND         Position_TFOM = 10
	Position_LTE_10_SECONDS       Position_TFOM = 11
	Position_LTE_100_SECONDS      Position_TFOM = 12
	Position_LTE_1000_SECONDS     Position_TFOM = 13
	Position_GT_1000_SECONDS      Position_TFOM = 14
)

var Position_TFOM_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "LTE_1_NANOSECOND",
	2:  "LTE_10_NANOSECONDS",
	3:  "LTE_100_NANOSECONDS",
	4:  "LTE_1_MICROSECOND",
	5:  "LTE_10_MICROSECONDS",
	6:  "LTE_100_MICROSECONDS",
	7:  "LTE_1_MILLISECOND",
	8:  "LTE_10_MILLISECONDS",
	9:  "LTE_100_MILLISECONDS",
	10: "LTE_1_SECOND",
	11: "LTE_10_SECONDS",
	12: "LTE_100_SECONDS",
	13: "LTE_1000_SECONDS",
	14: "GT_1000_SECONDS",
}

var Position_TFOM_value = map[string]int32{
	"UNSPECIFIED":          0,
	"LTE_1_NANOSECOND":     1,
	"LTE_10_NANOSECONDS":   2,
	"LTE_100_NANOSECONDS":  3,
	"LTE_1_MICROSECOND":    4,
	"LTE_10_MICROSECONDS":  5,
	"LTE_100_MICROSECONDS": 6,
	"LTE_1_MILLISECOND":    7,
	"LTE_10_MILLISECONDS":  8,
	"LTE_100_MILLISECONDS": 9,
	"LTE_1_SECOND":         10,
	"LTE_10_SECONDS":       11,
	"LTE_100_SECONDS":      12,
	"LTE_1000_SECONDS":     13,
	"GT_1000_SECONDS":      14,
}

func (x Position_TFOM) String() string {
	return proto.EnumName(Position_TFOM_name, int32(x))
}

func (Position_TFOM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{21, 0}
}

type PushRawMessageRequest struct {
	Message              *WrappedMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushRawMessageRequest) Reset()         { *m = PushRawMessageRequest{} }
func (m *PushRawMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PushRawMessageRequest) ProtoMessage()    {}
func (*PushRawMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{0}
}

func (m *PushRawMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRawMessageRequest.Unmarshal(m, b)
}
func (m *PushRawMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRawMessageRequest.Marshal(b, m, deterministic)
}
func (m *PushRawMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRawMessageRequest.Merge(m, src)
}
func (m *PushRawMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PushRawMessageRequest.Size(m)
}
func (m *PushRawMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRawMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRawMessageRequest proto.InternalMessageInfo

func (m *PushRawMessageRequest) GetMessage() *WrappedMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type PushRawMessageResponse struct {
	DuplicateDetails     *DuplicateDetails `protobuf:"bytes,2,opt,name=duplicate_details,json=duplicateDetails,proto3" json:"duplicate_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushRawMessageResponse) Reset()         { *m = PushRawMessageResponse{} }
func (m *PushRawMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PushRawMessageResponse) ProtoMessage()    {}
func (*PushRawMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{1}
}

func (m *PushRawMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRawMessageResponse.Unmarshal(m, b)
}
func (m *PushRawMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRawMessageResponse.Marshal(b, m, deterministic)
}
func (m *PushRawMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRawMessageResponse.Merge(m, src)
}
func (m *PushRawMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PushRawMessageResponse.Size(m)
}
func (m *PushRawMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRawMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushRawMessageResponse proto.InternalMessageInfo

func (m *PushRawMessageResponse) GetDuplicateDetails() *DuplicateDetails {
	if m != nil {
		return m.DuplicateDetails
	}
	return nil
}

type PushRawMessagesRequest struct {
	Metadata             *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserMetadata         []*UserDefinedMetadata `protobuf:"bytes,3,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	Messages             []*WrappedMessage      `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PushRawMessagesRequest) Reset()         { *m = PushRawMessagesRequest{} }
func (m *PushRawMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*PushRawMessagesRequest) ProtoMessage()    {}
func (*PushRawMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{2}
}

func (m *PushRawMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRawMessagesRequest.Unmarshal(m, b)
}
func (m *PushRawMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRawMessagesRequest.Marshal(b, m, deterministic)
}
func (m *PushRawMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRawMessagesRequest.Merge(m, src)
}
func (m *PushRawMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_PushRawMessagesRequest.Size(m)
}
func (m *PushRawMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRawMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRawMessagesRequest proto.InternalMessageInfo

func (m *PushRawMessagesRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PushRawMessagesRequest) GetUserMetadata() []*UserDefinedMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *PushRawMessagesRequest) GetMessages() []*WrappedMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PushRawMessagesResponse struct {
	DuplicateDetails     *DuplicateDetails `protobuf:"bytes,2,opt,name=duplicate_details,json=duplicateDetails,proto3" json:"duplicate_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushRawMessagesResponse) Reset()         { *m = PushRawMessagesResponse{} }
func (m *PushRawMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*PushRawMessagesResponse) ProtoMessage()    {}
func (*PushRawMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{3}
}

func (m *PushRawMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRawMessagesResponse.Unmarshal(m, b)
}
func (m *PushRawMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRawMessagesResponse.Marshal(b, m, deterministic)
}
func (m *PushRawMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRawMessagesResponse.Merge(m, src)
}
func (m *PushRawMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_PushRawMessagesResponse.Size(m)
}
func (m *PushRawMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRawMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushRawMessagesResponse proto.InternalMessageInfo

func (m *PushRawMessagesResponse) GetDuplicateDetails() *DuplicateDetails {
	if m != nil {
		return m.DuplicateDetails
	}
	return nil
}

type DuplicateDetails struct {
	Duplicates           bool     `protobuf:"varint,2,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	IdempotencyKeys      []string `protobuf:"bytes,3,rep,name=idempotency_keys,json=idempotencyKeys,proto3" json:"idempotency_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DuplicateDetails) Reset()         { *m = DuplicateDetails{} }
func (m *DuplicateDetails) String() string { return proto.CompactTextString(m) }
func (*DuplicateDetails) ProtoMessage()    {}
func (*DuplicateDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{4}
}

func (m *DuplicateDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateDetails.Unmarshal(m, b)
}
func (m *DuplicateDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateDetails.Marshal(b, m, deterministic)
}
func (m *DuplicateDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateDetails.Merge(m, src)
}
func (m *DuplicateDetails) XXX_Size() int {
	return xxx_messageInfo_DuplicateDetails.Size(m)
}
func (m *DuplicateDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateDetails proto.InternalMessageInfo

func (m *DuplicateDetails) GetDuplicates() bool {
	if m != nil {
		return m.Duplicates
	}
	return false
}

func (m *DuplicateDetails) GetIdempotencyKeys() []string {
	if m != nil {
		return m.IdempotencyKeys
	}
	return nil
}

type GetRawMessageRequest struct {
	RetrievalTypes        []MessageRetrievalType `protobuf:"varint,2,rep,packed,name=retrieval_types,json=retrievalTypes,proto3,enum=dlvc_api.MessageRetrievalType" json:"retrieval_types,omitempty"`
	ReturnedMetadataTypes []ReturnedMetadataType `protobuf:"varint,3,rep,packed,name=returned_metadata_types,json=returnedMetadataTypes,proto3,enum=dlvc_api.ReturnedMetadataType" json:"returned_metadata_types,omitempty"`
	Metadata              *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserMetadata          []*UserDefinedMetadata `protobuf:"bytes,5,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	SourceType            *SourceType            `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	BoundingBox           *PositionBoundingBox   `protobuf:"bytes,7,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	TimeRange             *TimeRange             `protobuf:"bytes,8,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	NextIndex             int64                  `protobuf:"varint,9,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *GetRawMessageRequest) Reset()         { *m = GetRawMessageRequest{} }
func (m *GetRawMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetRawMessageRequest) ProtoMessage()    {}
func (*GetRawMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{5}
}

func (m *GetRawMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawMessageRequest.Unmarshal(m, b)
}
func (m *GetRawMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetRawMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawMessageRequest.Merge(m, src)
}
func (m *GetRawMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetRawMessageRequest.Size(m)
}
func (m *GetRawMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawMessageRequest proto.InternalMessageInfo

func (m *GetRawMessageRequest) GetRetrievalTypes() []MessageRetrievalType {
	if m != nil {
		return m.RetrievalTypes
	}
	return nil
}

func (m *GetRawMessageRequest) GetReturnedMetadataTypes() []ReturnedMetadataType {
	if m != nil {
		return m.ReturnedMetadataTypes
	}
	return nil
}

func (m *GetRawMessageRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetRawMessageRequest) GetUserMetadata() []*UserDefinedMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *GetRawMessageRequest) GetSourceType() *SourceType {
	if m != nil {
		return m.SourceType
	}
	return nil
}

func (m *GetRawMessageRequest) GetBoundingBox() *PositionBoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *GetRawMessageRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *GetRawMessageRequest) GetNextIndex() int64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

type GetRawMessageResponse struct {
	Message              *WrappedMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextIndex            int64           `protobuf:"varint,3,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	LenBytes             int64           `protobuf:"varint,4,opt,name=len_bytes,json=lenBytes,proto3" json:"len_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRawMessageResponse) Reset()         { *m = GetRawMessageResponse{} }
func (m *GetRawMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetRawMessageResponse) ProtoMessage()    {}
func (*GetRawMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{6}
}

func (m *GetRawMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawMessageResponse.Unmarshal(m, b)
}
func (m *GetRawMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetRawMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawMessageResponse.Merge(m, src)
}
func (m *GetRawMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetRawMessageResponse.Size(m)
}
func (m *GetRawMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawMessageResponse proto.InternalMessageInfo

func (m *GetRawMessageResponse) GetMessage() *WrappedMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *GetRawMessageResponse) GetNextIndex() int64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *GetRawMessageResponse) GetLenBytes() int64 {
	if m != nil {
		return m.LenBytes
	}
	return 0
}

type GetRawMessagesRequest struct {
	RetrievalTypes        []MessageRetrievalType `protobuf:"varint,2,rep,packed,name=retrieval_types,json=retrievalTypes,proto3,enum=dlvc_api.MessageRetrievalType" json:"retrieval_types,omitempty"`
	ReturnedMetadataTypes []ReturnedMetadataType `protobuf:"varint,3,rep,packed,name=returned_metadata_types,json=returnedMetadataTypes,proto3,enum=dlvc_api.ReturnedMetadataType" json:"returned_metadata_types,omitempty"`
	Metadata              *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserMetadata          []*UserDefinedMetadata `protobuf:"bytes,5,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	SourceType            *SourceType            `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	BoundingBox           *PositionBoundingBox   `protobuf:"bytes,7,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	TimeRange             *TimeRange             `protobuf:"bytes,8,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	NextIndex             int64                  `protobuf:"varint,9,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	Limit                 int64                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	LenBytes              int64                  `protobuf:"varint,11,opt,name=len_bytes,json=lenBytes,proto3" json:"len_bytes,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *GetRawMessagesRequest) Reset()         { *m = GetRawMessagesRequest{} }
func (m *GetRawMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRawMessagesRequest) ProtoMessage()    {}
func (*GetRawMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{7}
}

func (m *GetRawMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawMessagesRequest.Unmarshal(m, b)
}
func (m *GetRawMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetRawMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawMessagesRequest.Merge(m, src)
}
func (m *GetRawMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRawMessagesRequest.Size(m)
}
func (m *GetRawMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawMessagesRequest proto.InternalMessageInfo

func (m *GetRawMessagesRequest) GetRetrievalTypes() []MessageRetrievalType {
	if m != nil {
		return m.RetrievalTypes
	}
	return nil
}

func (m *GetRawMessagesRequest) GetReturnedMetadataTypes() []ReturnedMetadataType {
	if m != nil {
		return m.ReturnedMetadataTypes
	}
	return nil
}

func (m *GetRawMessagesRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetRawMessagesRequest) GetUserMetadata() []*UserDefinedMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *GetRawMessagesRequest) GetSourceType() *SourceType {
	if m != nil {
		return m.SourceType
	}
	return nil
}

func (m *GetRawMessagesRequest) GetBoundingBox() *PositionBoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *GetRawMessagesRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *GetRawMessagesRequest) GetNextIndex() int64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *GetRawMessagesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRawMessagesRequest) GetLenBytes() int64 {
	if m != nil {
		return m.LenBytes
	}
	return 0
}

type GetRawMessagesResponse struct {
	Messages             []*WrappedMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	NextIndex            int64             `protobuf:"varint,3,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	LenBytes             int64             `protobuf:"varint,4,opt,name=len_bytes,json=lenBytes,proto3" json:"len_bytes,omitempty"`
	Count                int64             `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetRawMessagesResponse) Reset()         { *m = GetRawMessagesResponse{} }
func (m *GetRawMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRawMessagesResponse) ProtoMessage()    {}
func (*GetRawMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{8}
}

func (m *GetRawMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRawMessagesResponse.Unmarshal(m, b)
}
func (m *GetRawMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRawMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetRawMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRawMessagesResponse.Merge(m, src)
}
func (m *GetRawMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRawMessagesResponse.Size(m)
}
func (m *GetRawMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRawMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRawMessagesResponse proto.InternalMessageInfo

func (m *GetRawMessagesResponse) GetMessages() []*WrappedMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *GetRawMessagesResponse) GetNextIndex() int64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *GetRawMessagesResponse) GetLenBytes() int64 {
	if m != nil {
		return m.LenBytes
	}
	return 0
}

func (m *GetRawMessagesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SourceType struct {
	MessageType          WrappedMessage_MessageType   `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=dlvc_api.WrappedMessage_MessageType" json:"message_type,omitempty"`
	EncodingType         MessageEncoding_EncodingType `protobuf:"varint,3,opt,name=encoding_type,json=encodingType,proto3,enum=dlvc_api.MessageEncoding_EncodingType" json:"encoding_type,omitempty"`
	CustomEncodingType   string                       `protobuf:"bytes,4,opt,name=custom_encoding_type,json=customEncodingType,proto3" json:"custom_encoding_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SourceType) Reset()         { *m = SourceType{} }
func (m *SourceType) String() string { return proto.CompactTextString(m) }
func (*SourceType) ProtoMessage()    {}
func (*SourceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{9}
}

func (m *SourceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceType.Unmarshal(m, b)
}
func (m *SourceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceType.Marshal(b, m, deterministic)
}
func (m *SourceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceType.Merge(m, src)
}
func (m *SourceType) XXX_Size() int {
	return xxx_messageInfo_SourceType.Size(m)
}
func (m *SourceType) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceType.DiscardUnknown(m)
}

var xxx_messageInfo_SourceType proto.InternalMessageInfo

func (m *SourceType) GetMessageType() WrappedMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return WrappedMessage_UNSPECIFIED
}

func (m *SourceType) GetEncodingType() MessageEncoding_EncodingType {
	if m != nil {
		return m.EncodingType
	}
	return MessageEncoding_UNSPECIFIED
}

func (m *SourceType) GetCustomEncodingType() string {
	if m != nil {
		return m.CustomEncodingType
	}
	return ""
}

type TimeRange struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{10}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeRange) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type SummarizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummarizeRequest) Reset()         { *m = SummarizeRequest{} }
func (m *SummarizeRequest) String() string { return proto.CompactTextString(m) }
func (*SummarizeRequest) ProtoMessage()    {}
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{11}
}

func (m *SummarizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeRequest.Unmarshal(m, b)
}
func (m *SummarizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeRequest.Marshal(b, m, deterministic)
}
func (m *SummarizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeRequest.Merge(m, src)
}
func (m *SummarizeRequest) XXX_Size() int {
	return xxx_messageInfo_SummarizeRequest.Size(m)
}
func (m *SummarizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeRequest proto.InternalMessageInfo

type SummarizeResponse struct {
	MetadataKeys         []string                       `protobuf:"bytes,2,rep,name=metadata_keys,json=metadataKeys,proto3" json:"metadata_keys,omitempty"`
	UserMetadataKeys     []string                       `protobuf:"bytes,3,rep,name=user_metadata_keys,json=userMetadataKeys,proto3" json:"user_metadata_keys,omitempty"`
	MessageTypes         []WrappedMessage_MessageType   `protobuf:"varint,4,rep,packed,name=message_types,json=messageTypes,proto3,enum=dlvc_api.WrappedMessage_MessageType" json:"message_types,omitempty"`
	EncodingTypes        []MessageEncoding_EncodingType `protobuf:"varint,5,rep,packed,name=encoding_types,json=encodingTypes,proto3,enum=dlvc_api.MessageEncoding_EncodingType" json:"encoding_types,omitempty"`
	CustomEncodingTypes  []string                       `protobuf:"bytes,6,rep,name=custom_encoding_types,json=customEncodingTypes,proto3" json:"custom_encoding_types,omitempty"`
	LenBytes             int64                          `protobuf:"varint,7,opt,name=len_bytes,json=lenBytes,proto3" json:"len_bytes,omitempty"`
	Count                int64                          `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SummarizeResponse) Reset()         { *m = SummarizeResponse{} }
func (m *SummarizeResponse) String() string { return proto.CompactTextString(m) }
func (*SummarizeResponse) ProtoMessage()    {}
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{12}
}

func (m *SummarizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummarizeResponse.Unmarshal(m, b)
}
func (m *SummarizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummarizeResponse.Marshal(b, m, deterministic)
}
func (m *SummarizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummarizeResponse.Merge(m, src)
}
func (m *SummarizeResponse) XXX_Size() int {
	return xxx_messageInfo_SummarizeResponse.Size(m)
}
func (m *SummarizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummarizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummarizeResponse proto.InternalMessageInfo

func (m *SummarizeResponse) GetMetadataKeys() []string {
	if m != nil {
		return m.MetadataKeys
	}
	return nil
}

func (m *SummarizeResponse) GetUserMetadataKeys() []string {
	if m != nil {
		return m.UserMetadataKeys
	}
	return nil
}

func (m *SummarizeResponse) GetMessageTypes() []WrappedMessage_MessageType {
	if m != nil {
		return m.MessageTypes
	}
	return nil
}

func (m *SummarizeResponse) GetEncodingTypes() []MessageEncoding_EncodingType {
	if m != nil {
		return m.EncodingTypes
	}
	return nil
}

func (m *SummarizeResponse) GetCustomEncodingTypes() []string {
	if m != nil {
		return m.CustomEncodingTypes
	}
	return nil
}

func (m *SummarizeResponse) GetLenBytes() int64 {
	if m != nil {
		return m.LenBytes
	}
	return 0
}

func (m *SummarizeResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListMetadataValuesRequest struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMetadataValuesRequest) Reset()         { *m = ListMetadataValuesRequest{} }
func (m *ListMetadataValuesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMetadataValuesRequest) ProtoMessage()    {}
func (*ListMetadataValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{13}
}

func (m *ListMetadataValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMetadataValuesRequest.Unmarshal(m, b)
}
func (m *ListMetadataValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMetadataValuesRequest.Marshal(b, m, deterministic)
}
func (m *ListMetadataValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMetadataValuesRequest.Merge(m, src)
}
func (m *ListMetadataValuesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMetadataValuesRequest.Size(m)
}
func (m *ListMetadataValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMetadataValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMetadataValuesRequest proto.InternalMessageInfo

func (m *ListMetadataValuesRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ListMetadataValuesResponse struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMetadataValuesResponse) Reset()         { *m = ListMetadataValuesResponse{} }
func (m *ListMetadataValuesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMetadataValuesResponse) ProtoMessage()    {}
func (*ListMetadataValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{14}
}

func (m *ListMetadataValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMetadataValuesResponse.Unmarshal(m, b)
}
func (m *ListMetadataValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMetadataValuesResponse.Marshal(b, m, deterministic)
}
func (m *ListMetadataValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMetadataValuesResponse.Merge(m, src)
}
func (m *ListMetadataValuesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMetadataValuesResponse.Size(m)
}
func (m *ListMetadataValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMetadataValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMetadataValuesResponse proto.InternalMessageInfo

func (m *ListMetadataValuesResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListMetadataValuesResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ListExercisesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListExercisesRequest) Reset()         { *m = ListExercisesRequest{} }
func (m *ListExercisesRequest) String() string { return proto.CompactTextString(m) }
func (*ListExercisesRequest) ProtoMessage()    {}
func (*ListExercisesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{15}
}

func (m *ListExercisesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExercisesRequest.Unmarshal(m, b)
}
func (m *ListExercisesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExercisesRequest.Marshal(b, m, deterministic)
}
func (m *ListExercisesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExercisesRequest.Merge(m, src)
}
func (m *ListExercisesRequest) XXX_Size() int {
	return xxx_messageInfo_ListExercisesRequest.Size(m)
}
func (m *ListExercisesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExercisesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListExercisesRequest proto.InternalMessageInfo

type ListExercisesResponse struct {
	ExerciseIds          []string `protobuf:"bytes,3,rep,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListExercisesResponse) Reset()         { *m = ListExercisesResponse{} }
func (m *ListExercisesResponse) String() string { return proto.CompactTextString(m) }
func (*ListExercisesResponse) ProtoMessage()    {}
func (*ListExercisesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{16}
}

func (m *ListExercisesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExercisesResponse.Unmarshal(m, b)
}
func (m *ListExercisesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExercisesResponse.Marshal(b, m, deterministic)
}
func (m *ListExercisesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExercisesResponse.Merge(m, src)
}
func (m *ListExercisesResponse) XXX_Size() int {
	return xxx_messageInfo_ListExercisesResponse.Size(m)
}
func (m *ListExercisesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExercisesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListExercisesResponse proto.InternalMessageInfo

func (m *ListExercisesResponse) GetExerciseIds() []string {
	if m != nil {
		return m.ExerciseIds
	}
	return nil
}

type WrappedMessage struct {
	IdempotencyKey       string                     `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata             *Metadata                  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserMetadata         []*UserDefinedMetadata     `protobuf:"bytes,4,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	MessageType          WrappedMessage_MessageType `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=dlvc_api.WrappedMessage_MessageType" json:"message_type,omitempty"`
	MessageEncoding      *MessageEncoding           `protobuf:"bytes,6,opt,name=message_encoding,json=messageEncoding,proto3" json:"message_encoding,omitempty"`
	Position             *Position                  `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	CreatedTime          *timestamp.Timestamp       `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	RawMessage           []byte                     `protobuf:"bytes,9,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *WrappedMessage) Reset()         { *m = WrappedMessage{} }
func (m *WrappedMessage) String() string { return proto.CompactTextString(m) }
func (*WrappedMessage) ProtoMessage()    {}
func (*WrappedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{17}
}

func (m *WrappedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrappedMessage.Unmarshal(m, b)
}
func (m *WrappedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrappedMessage.Marshal(b, m, deterministic)
}
func (m *WrappedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrappedMessage.Merge(m, src)
}
func (m *WrappedMessage) XXX_Size() int {
	return xxx_messageInfo_WrappedMessage.Size(m)
}
func (m *WrappedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WrappedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WrappedMessage proto.InternalMessageInfo

func (m *WrappedMessage) GetIdempotencyKey() string {
	if m != nil {
		return m.IdempotencyKey
	}
	return ""
}

func (m *WrappedMessage) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WrappedMessage) GetUserMetadata() []*UserDefinedMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *WrappedMessage) GetMessageType() WrappedMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return WrappedMessage_UNSPECIFIED
}

func (m *WrappedMessage) GetMessageEncoding() *MessageEncoding {
	if m != nil {
		return m.MessageEncoding
	}
	return nil
}

func (m *WrappedMessage) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *WrappedMessage) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *WrappedMessage) GetRawMessage() []byte {
	if m != nil {
		return m.RawMessage
	}
	return nil
}

type Metadata struct {
	PartnerId            string              `protobuf:"bytes,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	PartnerCertId        string              `protobuf:"bytes,3,opt,name=partner_cert_id,json=partnerCertId,proto3" json:"partner_cert_id,omitempty"`
	SourceId             string              `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ExerciseId           string              `protobuf:"bytes,5,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	ExerciseName         string              `protobuf:"bytes,6,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	EntityStatePdu       string              `protobuf:"bytes,7,opt,name=entity_state_pdu,json=entityStatePdu,proto3" json:"entity_state_pdu,omitempty"`
	ForceColor           Metadata_ForceColor `protobuf:"varint,8,opt,name=force_color,json=forceColor,proto3,enum=dlvc_api.Metadata_ForceColor" json:"force_color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{18}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *Metadata) GetPartnerCertId() string {
	if m != nil {
		return m.PartnerCertId
	}
	return ""
}

func (m *Metadata) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *Metadata) GetExerciseId() string {
	if m != nil {
		return m.ExerciseId
	}
	return ""
}

func (m *Metadata) GetExerciseName() string {
	if m != nil {
		return m.ExerciseName
	}
	return ""
}

func (m *Metadata) GetEntityStatePdu() string {
	if m != nil {
		return m.EntityStatePdu
	}
	return ""
}

func (m *Metadata) GetForceColor() Metadata_ForceColor {
	if m != nil {
		return m.ForceColor
	}
	return Metadata_UNSPECIFIED
}

type UserDefinedMetadata struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ValueType            string   `protobuf:"bytes,4,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	UnitType             string   `protobuf:"bytes,5,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDefinedMetadata) Reset()         { *m = UserDefinedMetadata{} }
func (m *UserDefinedMetadata) String() string { return proto.CompactTextString(m) }
func (*UserDefinedMetadata) ProtoMessage()    {}
func (*UserDefinedMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{19}
}

func (m *UserDefinedMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDefinedMetadata.Unmarshal(m, b)
}
func (m *UserDefinedMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDefinedMetadata.Marshal(b, m, deterministic)
}
func (m *UserDefinedMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDefinedMetadata.Merge(m, src)
}
func (m *UserDefinedMetadata) XXX_Size() int {
	return xxx_messageInfo_UserDefinedMetadata.Size(m)
}
func (m *UserDefinedMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDefinedMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UserDefinedMetadata proto.InternalMessageInfo

func (m *UserDefinedMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UserDefinedMetadata) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UserDefinedMetadata) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

func (m *UserDefinedMetadata) GetUnitType() string {
	if m != nil {
		return m.UnitType
	}
	return ""
}

type MessageEncoding struct {
	EncodingType         MessageEncoding_EncodingType `protobuf:"varint,2,opt,name=encoding_type,json=encodingType,proto3,enum=dlvc_api.MessageEncoding_EncodingType" json:"encoding_type,omitempty"`
	CustomEncodingType   string                       `protobuf:"bytes,3,opt,name=custom_encoding_type,json=customEncodingType,proto3" json:"custom_encoding_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MessageEncoding) Reset()         { *m = MessageEncoding{} }
func (m *MessageEncoding) String() string { return proto.CompactTextString(m) }
func (*MessageEncoding) ProtoMessage()    {}
func (*MessageEncoding) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{20}
}

func (m *MessageEncoding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEncoding.Unmarshal(m, b)
}
func (m *MessageEncoding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEncoding.Marshal(b, m, deterministic)
}
func (m *MessageEncoding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEncoding.Merge(m, src)
}
func (m *MessageEncoding) XXX_Size() int {
	return xxx_messageInfo_MessageEncoding.Size(m)
}
func (m *MessageEncoding) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEncoding.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEncoding proto.InternalMessageInfo

func (m *MessageEncoding) GetEncodingType() MessageEncoding_EncodingType {
	if m != nil {
		return m.EncodingType
	}
	return MessageEncoding_UNSPECIFIED
}

func (m *MessageEncoding) GetCustomEncodingType() string {
	if m != nil {
		return m.CustomEncodingType
	}
	return ""
}

type Position struct {
	Latitude             float32       `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32       `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Pitch                float32       `protobuf:"fixed32,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw                  float32       `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Roll                 float32       `protobuf:"fixed32,6,opt,name=roll,proto3" json:"roll,omitempty"`
	RadiusMeters         float32       `protobuf:"fixed32,7,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	ResolutionMeters     float32       `protobuf:"fixed32,8,opt,name=resolution_meters,json=resolutionMeters,proto3" json:"resolution_meters,omitempty"`
	Tfom                 Position_TFOM `protobuf:"varint,9,opt,name=tfom,proto3,enum=dlvc_api.Position_TFOM" json:"tfom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{21}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Position) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Position) GetPitch() float32 {
	if m != nil {
		return m.Pitch
	}
	return 0
}

func (m *Position) GetYaw() float32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *Position) GetRoll() float32 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *Position) GetRadiusMeters() float32 {
	if m != nil {
		return m.RadiusMeters
	}
	return 0
}

func (m *Position) GetResolutionMeters() float32 {
	if m != nil {
		return m.ResolutionMeters
	}
	return 0
}

func (m *Position) GetTfom() Position_TFOM {
	if m != nil {
		return m.Tfom
	}
	return Position_UNSPECIFIED
}

type PositionBoundingBox struct {
	MinLatitude          float32  `protobuf:"fixed32,2,opt,name=min_latitude,json=minLatitude,proto3" json:"min_latitude,omitempty"`
	MaxLatitude          float32  `protobuf:"fixed32,3,opt,name=max_latitude,json=maxLatitude,proto3" json:"max_latitude,omitempty"`
	MinLongitude         float32  `protobuf:"fixed32,4,opt,name=min_longitude,json=minLongitude,proto3" json:"min_longitude,omitempty"`
	MaxLongitude         float32  `protobuf:"fixed32,5,opt,name=max_longitude,json=maxLongitude,proto3" json:"max_longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionBoundingBox) Reset()         { *m = PositionBoundingBox{} }
func (m *PositionBoundingBox) String() string { return proto.CompactTextString(m) }
func (*PositionBoundingBox) ProtoMessage()    {}
func (*PositionBoundingBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_8074a668587a7e0c, []int{22}
}

func (m *PositionBoundingBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionBoundingBox.Unmarshal(m, b)
}
func (m *PositionBoundingBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionBoundingBox.Marshal(b, m, deterministic)
}
func (m *PositionBoundingBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionBoundingBox.Merge(m, src)
}
func (m *PositionBoundingBox) XXX_Size() int {
	return xxx_messageInfo_PositionBoundingBox.Size(m)
}
func (m *PositionBoundingBox) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionBoundingBox.DiscardUnknown(m)
}

var xxx_messageInfo_PositionBoundingBox proto.InternalMessageInfo

func (m *PositionBoundingBox) GetMinLatitude() float32 {
	if m != nil {
		return m.MinLatitude
	}
	return 0
}

func (m *PositionBoundingBox) GetMaxLatitude() float32 {
	if m != nil {
		return m.MaxLatitude
	}
	return 0
}

func (m *PositionBoundingBox) GetMinLongitude() float32 {
	if m != nil {
		return m.MinLongitude
	}
	return 0
}

func (m *PositionBoundingBox) GetMaxLongitude() float32 {
	if m != nil {
		return m.MaxLongitude
	}
	return 0
}

func init() {
	proto.RegisterEnum("dlvc_api.MessageRetrievalType", MessageRetrievalType_name, MessageRetrievalType_value)
	proto.RegisterEnum("dlvc_api.ReturnedMetadataType", ReturnedMetadataType_name, ReturnedMetadataType_value)
	proto.RegisterEnum("dlvc_api.WrappedMessage_MessageType", WrappedMessage_MessageType_name, WrappedMessage_MessageType_value)
	proto.RegisterEnum("dlvc_api.Metadata_ForceColor", Metadata_ForceColor_name, Metadata_ForceColor_value)
	proto.RegisterEnum("dlvc_api.MessageEncoding_EncodingType", MessageEncoding_EncodingType_name, MessageEncoding_EncodingType_value)
	proto.RegisterEnum("dlvc_api.Position_TFOM", Position_TFOM_name, Position_TFOM_value)
	proto.RegisterType((*PushRawMessageRequest)(nil), "dlvc_api.PushRawMessageRequest")
	proto.RegisterType((*PushRawMessageResponse)(nil), "dlvc_api.PushRawMessageResponse")
	proto.RegisterType((*PushRawMessagesRequest)(nil), "dlvc_api.PushRawMessagesRequest")
	proto.RegisterType((*PushRawMessagesResponse)(nil), "dlvc_api.PushRawMessagesResponse")
	proto.RegisterType((*DuplicateDetails)(nil), "dlvc_api.DuplicateDetails")
	proto.RegisterType((*GetRawMessageRequest)(nil), "dlvc_api.GetRawMessageRequest")
	proto.RegisterType((*GetRawMessageResponse)(nil), "dlvc_api.GetRawMessageResponse")
	proto.RegisterType((*GetRawMessagesRequest)(nil), "dlvc_api.GetRawMessagesRequest")
	proto.RegisterType((*GetRawMessagesResponse)(nil), "dlvc_api.GetRawMessagesResponse")
	proto.RegisterType((*SourceType)(nil), "dlvc_api.SourceType")
	proto.RegisterType((*TimeRange)(nil), "dlvc_api.TimeRange")
	proto.RegisterType((*SummarizeRequest)(nil), "dlvc_api.SummarizeRequest")
	proto.RegisterType((*SummarizeResponse)(nil), "dlvc_api.SummarizeResponse")
	proto.RegisterType((*ListMetadataValuesRequest)(nil), "dlvc_api.ListMetadataValuesRequest")
	proto.RegisterType((*ListMetadataValuesResponse)(nil), "dlvc_api.ListMetadataValuesResponse")
	proto.RegisterType((*ListExercisesRequest)(nil), "dlvc_api.ListExercisesRequest")
	proto.RegisterType((*ListExercisesResponse)(nil), "dlvc_api.ListExercisesResponse")
	proto.RegisterType((*WrappedMessage)(nil), "dlvc_api.WrappedMessage")
	proto.RegisterType((*Metadata)(nil), "dlvc_api.Metadata")
	proto.RegisterType((*UserDefinedMetadata)(nil), "dlvc_api.UserDefinedMetadata")
	proto.RegisterType((*MessageEncoding)(nil), "dlvc_api.MessageEncoding")
	proto.RegisterType((*Position)(nil), "dlvc_api.Position")
	proto.RegisterType((*PositionBoundingBox)(nil), "dlvc_api.PositionBoundingBox")
}

func init() { proto.RegisterFile("dlvc_api/dlvc.proto", fileDescriptor_8074a668587a7e0c) }

var fileDescriptor_8074a668587a7e0c = []byte{
	// 1856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x73, 0xdc, 0x48,
	0x15, 0x67, 0xa4, 0x19, 0x5b, 0x7a, 0x33, 0x9e, 0x69, 0xb7, 0xc7, 0xc9, 0x24, 0x9b, 0xec, 0x06,
	0x43, 0x2d, 0x66, 0xa1, 0x9c, 0xac, 0x97, 0x85, 0xe2, 0x00, 0xb5, 0xf6, 0x8c, 0x6c, 0x94, 0xcc,
	0x68, 0xbc, 0x2d, 0x39, 0x1b, 0x4e, 0x2a, 0x79, 0xd4, 0x76, 0x54, 0x3b, 0x23, 0x0d, 0xfa, 0x93,
	0xd8, 0x5c, 0x38, 0x70, 0xe6, 0x63, 0xc0, 0x85, 0x13, 0xdf, 0x80, 0x03, 0x07, 0x3e, 0x02, 0xc5,
	0x89, 0x2b, 0x55, 0xf0, 0x11, 0xa8, 0xa2, 0xba, 0xd5, 0x2d, 0x69, 0xfe, 0xb8, 0x92, 0x0d, 0xb5,
	0x27, 0xf6, 0xa6, 0xfe, 0xbd, 0xdf, 0x7b, 0xfd, 0xe7, 0xfd, 0xfa, 0xbd, 0x16, 0xec, 0xf8, 0xd3,
	0x57, 0x13, 0xd7, 0x9b, 0x07, 0x8f, 0xd9, 0xc7, 0xc1, 0x3c, 0x8e, 0xd2, 0x08, 0x6b, 0x12, 0xbc,
	0xff, 0xc1, 0x55, 0x14, 0x5d, 0x4d, 0xe9, 0x63, 0x8e, 0x5f, 0x64, 0x97, 0x8f, 0xd3, 0x60, 0x46,
	0x93, 0xd4, 0x9b, 0xcd, 0x73, 0xea, 0xde, 0xe7, 0xb0, 0x7b, 0x96, 0x25, 0x2f, 0x89, 0xf7, 0x7a,
	0x44, 0x93, 0xc4, 0xbb, 0xa2, 0x84, 0xfe, 0x2a, 0xa3, 0x49, 0x8a, 0x0f, 0x61, 0x73, 0x96, 0x23,
	0x3d, 0xe5, 0x51, 0x6d, 0xbf, 0x79, 0xd8, 0x3b, 0x90, 0x51, 0x0f, 0xbe, 0x88, 0xbd, 0xf9, 0x9c,
	0xfa, 0xd2, 0x43, 0x12, 0x9f, 0xd6, 0xb5, 0x1a, 0x52, 0xf6, 0xae, 0xe0, 0xce, 0x72, 0xc8, 0x64,
	0x1e, 0x85, 0x09, 0xc5, 0xa7, 0xb0, 0xed, 0x67, 0xf3, 0x69, 0x30, 0xf1, 0x52, 0xea, 0xfa, 0x34,
	0xf5, 0x82, 0x69, 0x22, 0xa2, 0xdf, 0x2f, 0xa3, 0x0f, 0x24, 0x65, 0x90, 0x33, 0x08, 0xf2, 0x97,
	0x10, 0x31, 0xd1, 0x5f, 0x6b, 0xcb, 0x33, 0x25, 0x72, 0xf5, 0x07, 0xa0, 0xcd, 0x68, 0xea, 0xf9,
	0x5e, 0xea, 0x89, 0x09, 0x70, 0x39, 0xc1, 0x48, 0x58, 0x48, 0xc1, 0xc1, 0xc7, 0xb0, 0x95, 0x25,
	0x34, 0x76, 0x0b, 0x27, 0xf5, 0x91, 0xba, 0xdf, 0x3c, 0x7c, 0x58, 0x3a, 0x9d, 0x27, 0x34, 0x1e,
	0xd0, 0xcb, 0x20, 0x64, 0xfb, 0x16, 0xfe, 0x2d, 0xe6, 0x23, 0x47, 0xf8, 0x47, 0x6c, 0xce, 0x7c,
	0x19, 0xbd, 0x3a, 0x77, 0xbf, 0xfd, 0xc8, 0x0a, 0xa6, 0xd8, 0xca, 0x4b, 0xb8, 0xbb, 0xb2, 0x93,
	0xaf, 0xe7, 0xd0, 0x26, 0x80, 0x96, 0xb9, 0xf8, 0x7d, 0x80, 0x82, 0x9d, 0xc7, 0xd6, 0x48, 0x05,
	0xc1, 0xdf, 0x07, 0x14, 0xf8, 0x74, 0x36, 0x8f, 0x52, 0x1a, 0x4e, 0x6e, 0xdc, 0x2f, 0xe9, 0x4d,
	0xc2, 0x0f, 0x48, 0x27, 0x9d, 0x0a, 0xfe, 0x8c, 0xde, 0xc8, 0x49, 0xfe, 0xa3, 0x42, 0xf7, 0x94,
	0xa6, 0xab, 0xaa, 0x3a, 0x85, 0x4e, 0x4c, 0xd3, 0x38, 0xa0, 0xaf, 0xbc, 0xa9, 0x9b, 0xde, 0xcc,
	0xf9, 0x74, 0xea, 0x7e, 0xfb, 0xf0, 0xfd, 0x6a, 0x7a, 0x84, 0x8b, 0xe0, 0x39, 0x37, 0x73, 0x4a,
	0xda, 0x71, 0x75, 0x98, 0xe0, 0xe7, 0x70, 0x37, 0xa6, 0x69, 0x16, 0x87, 0xd4, 0x2f, 0x92, 0x26,
	0x02, 0xaa, 0xcb, 0x01, 0x89, 0x20, 0xca, 0x4c, 0xf1, 0x80, 0xbb, 0xf1, 0x1a, 0x34, 0x59, 0x10,
	0x4e, 0xfd, 0x5d, 0x84, 0xd3, 0xf8, 0xea, 0xc2, 0xf9, 0x14, 0x9a, 0x49, 0x94, 0xc5, 0x13, 0xca,
	0x37, 0xd0, 0xdb, 0xe0, 0xd3, 0x76, 0xcb, 0x08, 0x36, 0x37, 0xf2, 0x55, 0x43, 0x52, 0x7c, 0xe3,
	0xcf, 0xa0, 0x75, 0x11, 0x65, 0xa1, 0x1f, 0x84, 0x57, 0xee, 0x45, 0x74, 0xdd, 0xdb, 0xe4, 0x7e,
	0x95, 0x99, 0xcf, 0xa2, 0x24, 0x48, 0x83, 0x28, 0x3c, 0x16, 0xac, 0xe3, 0xe8, 0x9a, 0x34, 0x2f,
	0xca, 0x01, 0x3e, 0x04, 0x60, 0xf5, 0xc0, 0x8d, 0xbd, 0xf0, 0x8a, 0xf6, 0x34, 0xee, 0xbf, 0x53,
	0xfa, 0x3b, 0xc1, 0x8c, 0x12, 0x66, 0x22, 0x7a, 0x2a, 0x3f, 0xf1, 0x43, 0x80, 0x90, 0x5e, 0xa7,
	0x6e, 0x10, 0xfa, 0xf4, 0xba, 0xa7, 0x3f, 0xaa, 0xed, 0xab, 0x44, 0x67, 0x88, 0xc9, 0x00, 0x91,
	0xff, 0xdf, 0xd5, 0x60, 0x77, 0x29, 0xff, 0x42, 0xcd, 0xef, 0x50, 0x56, 0x96, 0xa6, 0x54, 0x97,
	0xa6, 0xc4, 0xef, 0x81, 0x3e, 0xa5, 0xa1, 0x7b, 0x71, 0x93, 0xf2, 0x8b, 0xc7, 0xac, 0xda, 0x94,
	0x86, 0xc7, 0x6c, 0x2c, 0xd6, 0xf3, 0xa7, 0xfa, 0xd2, 0x7a, 0x92, 0x6f, 0x04, 0xf9, 0xff, 0x21,
	0x48, 0xdc, 0x85, 0xc6, 0x34, 0x98, 0x05, 0x69, 0x0f, 0xb8, 0x25, 0x1f, 0x2c, 0x6a, 0xa6, 0xb9,
	0x56, 0x33, 0x7f, 0xa8, 0xc1, 0x9d, 0x65, 0xcd, 0x08, 0x11, 0x57, 0x2b, 0xbd, 0xf2, 0xb6, 0x95,
	0xfe, 0x7f, 0x91, 0x31, 0xdb, 0xc5, 0x24, 0xca, 0xc2, 0xb4, 0xd7, 0xc8, 0x77, 0xc1, 0x07, 0x62,
	0xa1, 0x7f, 0xaf, 0x01, 0x94, 0x19, 0xc1, 0xa7, 0xd0, 0x12, 0x53, 0xe6, 0xd9, 0x63, 0xd7, 0xac,
	0x7d, 0xf8, 0xdd, 0xdb, 0x16, 0x28, 0xd5, 0xcd, 0xb3, 0xd9, 0x9c, 0x95, 0x03, 0xfc, 0x0c, 0xb6,
	0x68, 0x38, 0x89, 0x78, 0x3a, 0x79, 0x24, 0x95, 0x47, 0xfa, 0x70, 0xe5, 0x62, 0x18, 0x82, 0x75,
	0x20, 0x3f, 0x78, 0xac, 0x16, 0xad, 0x8c, 0xf0, 0x13, 0xe8, 0x4e, 0xb2, 0x24, 0x8d, 0x66, 0xee,
	0x62, 0x4c, 0xb6, 0x51, 0x9d, 0xe0, 0xdc, 0x56, 0xf5, 0x17, 0x9b, 0xfb, 0x6d, 0x0d, 0xf4, 0x22,
	0xed, 0xf8, 0xa7, 0x00, 0x49, 0xea, 0xc5, 0xa9, 0xcb, 0xd2, 0x5f, 0x34, 0xc1, 0xfc, 0x8d, 0x73,
	0x20, 0xdf, 0x38, 0x5c, 0x26, 0xfc, 0x8d, 0x43, 0x74, 0xce, 0x66, 0x63, 0xfc, 0x29, 0x68, 0x34,
	0xf4, 0x73, 0x47, 0xf5, 0x8d, 0x8e, 0x9b, 0x34, 0xf4, 0xd9, 0x48, 0xac, 0xa2, 0x07, 0xc8, 0xce,
	0x66, 0x33, 0x2f, 0x0e, 0x7e, 0x2d, 0x5b, 0x99, 0xb0, 0xfc, 0x5b, 0x81, 0xed, 0x8a, 0x49, 0x08,
	0xe4, 0x3b, 0xb0, 0x55, 0xd4, 0x00, 0xde, 0x2d, 0x15, 0xde, 0x2d, 0x5b, 0x12, 0x64, 0xad, 0x12,
	0xff, 0x10, 0xf0, 0xc2, 0x4d, 0xad, 0xf6, 0x55, 0x54, 0xbd, 0x8f, 0x9c, 0x6d, 0xb2, 0x90, 0x65,
	0x5a, 0xf3, 0x27, 0xc6, 0xdb, 0xe6, 0xb5, 0x55, 0xc9, 0x6b, 0x82, 0x47, 0xd0, 0x5e, 0x48, 0x42,
	0xc2, 0x6b, 0xc4, 0xdb, 0x67, 0x76, 0xab, 0x9a, 0xd9, 0x04, 0x1f, 0xc2, 0xee, 0xba, 0xd4, 0x26,
	0xbd, 0x0d, 0xbe, 0x95, 0x9d, 0xd5, 0xdc, 0x26, 0x8b, 0x62, 0xdf, 0xbc, 0x4d, 0xec, 0xda, 0xaa,
	0xd8, 0x3f, 0x81, 0x7b, 0xc3, 0x20, 0x49, 0xe5, 0xd1, 0x3c, 0xf7, 0xa6, 0x59, 0x59, 0xcc, 0x11,
	0xa8, 0x5f, 0xd2, 0x1b, 0xae, 0x0b, 0x9d, 0xb0, 0x4f, 0xe1, 0x34, 0x84, 0xfb, 0xeb, 0x9c, 0x44,
	0xb2, 0x56, 0xbc, 0xf0, 0x1d, 0xd8, 0x78, 0xc5, 0x39, 0x22, 0x1b, 0x62, 0x24, 0xa2, 0x3d, 0x80,
	0x2e, 0x8b, 0x66, 0x5c, 0xd3, 0x78, 0x12, 0x24, 0xc5, 0xec, 0xc2, 0xfa, 0x19, 0xec, 0x2e, 0x59,
	0xc5, 0x34, 0xdf, 0x86, 0x16, 0x15, 0xa0, 0x1b, 0xf8, 0x32, 0x74, 0x53, 0x62, 0xa6, 0x2f, 0xe3,
	0xff, 0xb9, 0x0e, 0xed, 0xc5, 0x5c, 0xe2, 0xef, 0x41, 0x67, 0xe9, 0x01, 0x26, 0x96, 0xdb, 0x5e,
	0x7c, 0x7f, 0x2d, 0x74, 0x0b, 0xf5, 0x5d, 0xba, 0x45, 0xfd, 0xab, 0x77, 0x8b, 0xe5, 0x82, 0xd3,
	0x78, 0xd7, 0x82, 0x33, 0x00, 0x24, 0x03, 0x49, 0x25, 0x89, 0xde, 0x73, 0xef, 0x56, 0x65, 0x92,
	0xce, 0x6c, 0x11, 0x60, 0x47, 0x30, 0x17, 0x7d, 0x46, 0x74, 0x20, 0xbc, 0xda, 0x81, 0x48, 0xc1,
	0xc1, 0x3f, 0x83, 0xd6, 0x24, 0xa6, 0x5e, 0x4a, 0x45, 0x71, 0xd0, 0xde, 0x58, 0x1c, 0x9a, 0x82,
	0xcf, 0xeb, 0xca, 0x07, 0xd0, 0x8c, 0xbd, 0xd7, 0xae, 0x7c, 0xd4, 0xb0, 0xfe, 0xd3, 0x22, 0x10,
	0x17, 0x5d, 0x63, 0x6f, 0x0a, 0xcd, 0xca, 0x8e, 0x71, 0x07, 0x9a, 0xe7, 0x96, 0x7d, 0x66, 0xf4,
	0xcd, 0x13, 0xd3, 0x18, 0xa0, 0x6f, 0x61, 0x80, 0x8d, 0xfe, 0xb9, 0xed, 0x8c, 0x47, 0xa8, 0x86,
	0x35, 0xa8, 0x0f, 0x4c, 0xfb, 0x27, 0x48, 0xc1, 0x9b, 0xa0, 0xf6, 0xc7, 0x0e, 0x52, 0x99, 0x79,
	0x68, 0x5a, 0xcf, 0x3e, 0xfe, 0x31, 0xaa, 0x63, 0x1d, 0x1a, 0x4f, 0x89, 0x71, 0x74, 0x86, 0x1a,
	0xf8, 0x0e, 0x60, 0xd3, 0xb2, 0x1d, 0x72, 0xde, 0x77, 0xc6, 0xc4, 0xed, 0x8f, 0x47, 0x23, 0xc3,
	0x72, 0xd0, 0x86, 0x90, 0xd0, 0xbf, 0x14, 0xd0, 0x8a, 0xfc, 0x3c, 0x04, 0x98, 0x7b, 0x71, 0x1a,
	0xd2, 0xd8, 0x0d, 0x7c, 0xa1, 0x1b, 0x5d, 0x20, 0xa6, 0x8f, 0x3f, 0x84, 0x8e, 0x34, 0x4f, 0x68,
	0x9c, 0x32, 0x8e, 0xca, 0x39, 0x5b, 0x02, 0xee, 0xd3, 0x38, 0x35, 0x7d, 0x76, 0x65, 0xc5, 0xa3,
	0x20, 0xf0, 0x45, 0xd9, 0xd6, 0x72, 0xc0, 0xf4, 0xd9, 0x29, 0x54, 0xc4, 0xcd, 0x25, 0xa0, 0x13,
	0x28, 0xb5, 0xcd, 0x2a, 0x62, 0x41, 0x08, 0xbd, 0x59, 0xfe, 0xa8, 0xd0, 0x49, 0x71, 0x25, 0x2c,
	0x6f, 0x46, 0xf1, 0x3e, 0x20, 0x1a, 0xa6, 0x41, 0x7a, 0xe3, 0x26, 0x29, 0xfb, 0xdb, 0x99, 0xfb,
	0x19, 0x4f, 0xa1, 0x4e, 0xda, 0x39, 0x6e, 0x33, 0xf8, 0xcc, 0xcf, 0xf0, 0xcf, 0xa1, 0x79, 0x19,
	0xb1, 0xb5, 0x4c, 0xa2, 0x69, 0x14, 0xf3, 0x9c, 0xb5, 0xab, 0xaa, 0x95, 0x9b, 0x3f, 0x38, 0x61,
	0xac, 0x3e, 0x23, 0x11, 0xb8, 0x2c, 0xbe, 0xf7, 0x4e, 0x00, 0x4a, 0xcb, 0x6a, 0x4e, 0x34, 0xa8,
	0x1f, 0x0f, 0xcf, 0x0d, 0x54, 0x63, 0x79, 0x20, 0xc6, 0x00, 0x29, 0xec, 0xec, 0xbf, 0xf8, 0x85,
	0xe9, 0x18, 0x48, 0x65, 0x9f, 0xa7, 0xc4, 0x30, 0x2c, 0x54, 0x17, 0xc7, 0xfd, 0x1b, 0xd8, 0x59,
	0x73, 0x4d, 0xd6, 0x14, 0x96, 0x2e, 0x34, 0x78, 0x29, 0x11, 0x27, 0x9c, 0x0f, 0x58, 0x82, 0xf8,
	0x47, 0xb5, 0x23, 0xea, 0x1c, 0xe1, 0x8a, 0x79, 0x0f, 0xf4, 0x2c, 0x0c, 0xd2, 0xf2, 0x72, 0xe9,
	0x44, 0x63, 0x40, 0xa5, 0x4b, 0xfe, 0xb3, 0x06, 0x9d, 0xa5, 0x8b, 0xb1, 0xda, 0xbe, 0x95, 0xaf,
	0xa1, 0x7d, 0xab, 0xb7, 0xb5, 0xef, 0xbd, 0xcf, 0xa1, 0x55, 0x1d, 0xbf, 0x51, 0xf7, 0x8e, 0xf1,
	0xc2, 0x41, 0x0a, 0xfb, 0x7a, 0x6a, 0x8f, 0x2d, 0xa4, 0xb2, 0x93, 0x7f, 0x31, 0x1a, 0xa2, 0x3a,
	0xbf, 0x0a, 0xf6, 0x73, 0xd4, 0x10, 0x7b, 0xfd, 0x47, 0x1d, 0x34, 0x79, 0x8d, 0xf1, 0x7d, 0xd0,
	0xa6, 0x5e, 0x1a, 0xa4, 0x99, 0x9f, 0xef, 0x4f, 0x21, 0xc5, 0x18, 0x3f, 0x00, 0x7d, 0x1a, 0x85,
	0x57, 0xb9, 0x51, 0xe5, 0xc6, 0x12, 0x60, 0xa9, 0x98, 0x07, 0xe9, 0xe4, 0x25, 0x3f, 0x6f, 0x85,
	0xe4, 0x03, 0x96, 0xb2, 0x1b, 0xef, 0x35, 0x3f, 0x65, 0x85, 0xb0, 0x4f, 0x8c, 0xa1, 0x1e, 0x47,
	0xd3, 0x29, 0xd7, 0xab, 0x42, 0xf8, 0x37, 0x13, 0x73, 0xec, 0xf9, 0x41, 0x96, 0xb0, 0xba, 0x49,
	0xe3, 0xbc, 0x83, 0x29, 0xa4, 0x95, 0x83, 0x23, 0x8e, 0xe1, 0x1f, 0xc0, 0x76, 0x4c, 0x93, 0x68,
	0x9a, 0xb1, 0x85, 0x4a, 0xa2, 0xc6, 0x89, 0xa8, 0x34, 0x14, 0xe4, 0x7a, 0x7a, 0x19, 0xcd, 0x78,
	0xf9, 0x68, 0x1f, 0xde, 0x5d, 0x2d, 0x58, 0x07, 0xce, 0xc9, 0x78, 0x44, 0x38, 0x69, 0xef, 0x6f,
	0x0a, 0xd4, 0xd9, 0x70, 0xf5, 0x4c, 0xbb, 0x80, 0x86, 0x8e, 0xe1, 0x7e, 0xec, 0x5a, 0x47, 0xd6,
	0xd8, 0x36, 0xfa, 0x63, 0x6b, 0x80, 0x6a, 0xac, 0x56, 0x70, 0xf4, 0x49, 0x05, 0xb6, 0x91, 0x82,
	0xef, 0xc2, 0x4e, 0x8e, 0x2f, 0x1a, 0x54, 0xbc, 0x0b, 0xdb, 0x79, 0x98, 0x91, 0xd9, 0x27, 0x32,
	0x4e, 0xbd, 0xe4, 0x57, 0x71, 0x1b, 0x35, 0x70, 0x0f, 0xba, 0x32, 0xd0, 0x82, 0x65, 0xa3, 0x1a,
	0x69, 0x38, 0x34, 0x45, 0xa4, 0xcd, 0x85, 0x48, 0x05, 0x6e, 0x23, 0x6d, 0x31, 0x52, 0xc5, 0xa2,
	0x63, 0x04, 0xad, 0x3c, 0x92, 0x08, 0x02, 0x18, 0x43, 0x5b, 0x04, 0x91, 0xac, 0x26, 0xde, 0x81,
	0x8e, 0xf4, 0x97, 0x60, 0xab, 0x38, 0x95, 0x27, 0x15, 0x74, 0x8b, 0x51, 0x4f, 0x9d, 0x45, 0xb0,
	0x2d, 0x24, 0xf6, 0xc7, 0x1a, 0xec, 0xac, 0xf9, 0x57, 0x61, 0x2d, 0x7c, 0x16, 0x84, 0xee, 0x92,
	0xe2, 0x9a, 0xb3, 0x20, 0x1c, 0x4a, 0xd1, 0x31, 0x8a, 0x77, 0x5d, 0x52, 0x54, 0x41, 0xf1, 0xae,
	0x0b, 0x0a, 0x7b, 0x1c, 0xb2, 0x28, 0x85, 0x36, 0x73, 0x05, 0xb2, 0xd0, 0xc3, 0x42, 0x9e, 0x8c,
	0xc4, 0xe2, 0x14, 0xa4, 0x86, 0x20, 0x79, 0xd7, 0x05, 0x29, 0x5f, 0xed, 0x47, 0xbf, 0xaf, 0x41,
	0x77, 0xdd, 0x2f, 0xea, 0xaa, 0x3c, 0x74, 0x68, 0x98, 0xd6, 0xc0, 0x78, 0x21, 0x6e, 0x9c, 0x39,
	0x32, 0x90, 0xc2, 0x0e, 0x76, 0x64, 0xd8, 0xf6, 0xd1, 0xa9, 0xe1, 0x3a, 0xbf, 0x3c, 0x63, 0xf5,
	0x6d, 0x1b, 0xb6, 0x0c, 0xab, 0x3f, 0x1e, 0x98, 0xd6, 0x69, 0x0e, 0xd5, 0x71, 0x0b, 0xb4, 0x91,
	0xe1, 0x1c, 0x0d, 0x8e, 0x9c, 0x23, 0xd4, 0xc0, 0xf7, 0x60, 0xf7, 0xdc, 0x36, 0x88, 0x3b, 0x30,
	0x4e, 0x4c, 0xcb, 0x18, 0xb8, 0x85, 0x69, 0x83, 0x99, 0xce, 0xc6, 0xb6, 0xe9, 0x98, 0x63, 0xcb,
	0x3d, 0x1e, 0x9f, 0x5b, 0x3c, 0xc8, 0xf1, 0xf8, 0x05, 0xda, 0xfc, 0xe8, 0x2f, 0x35, 0xe8, 0xae,
	0xfb, 0xf3, 0x65, 0xfa, 0x24, 0x86, 0x73, 0x4e, 0x2c, 0x77, 0x71, 0xb9, 0x1d, 0x68, 0x0a, 0xdc,
	0x1a, 0x5b, 0xac, 0x18, 0xb7, 0x01, 0x04, 0x70, 0x34, 0x1c, 0x22, 0xa5, 0x42, 0xe0, 0x7b, 0x51,
	0x2b, 0x91, 0xec, 0xf1, 0x39, 0xe9, 0x1b, 0x72, 0xf9, 0x3b, 0xd0, 0x11, 0x78, 0x65, 0x17, 0x8f,
	0xe0, 0x81, 0x9c, 0xf6, 0x96, 0xcd, 0x94, 0x6e, 0x72, 0x4f, 0x68, 0xf3, 0x62, 0x83, 0xbf, 0x08,
	0x3e, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xf3, 0x9f, 0x74, 0x7a, 0x15, 0x00, 0x00,
}
